Fixed __zk rmr bug

diff --git a/ansible/templates/usb/scripts/computenode.sh.j2 b/ansible/templates/usb/scripts/computenode.sh.j2
--- a/ansible/templates/usb/scripts/computenode.sh.j2
+++ b/ansible/templates/usb/scripts/computenode.sh.j2
@@ -124,13 +124,13 @@ function __zk() {
 	zkcli="${USB_COPY}/scripts/zookeepercli"
 	args="${@}"
 
-	if ! "${zkcli}" -servers "${CFGDB_IP}:2181" -auth_usr "esdc" -auth_pwd "${ESDC_INSTALL_PASSWORD}" ${args} 2> /dev/null; then
-		fatal "Error: cfgdb command \"${cmd}\" failed"
-	fi
+	"${zkcli}" -servers "${CFGDB_IP}:2181" -auth_usr "esdc" -auth_pwd "${ESDC_INSTALL_PASSWORD}" ${args}
 }
 
 function _zk() {
-	__zk -c "${@}"
+	if ! __zk -c "${@}" 2> /dev/null; then
+		fatal "Error: cfgdb command \"${cmd}\" failed"
+	fi
 }
 
 function wait_for_cfgdb() {
@@ -164,7 +164,9 @@ function query_cfgdb() {
 
 	printf_log "%-56s Registering compute node into cfgdb ..."
 
-	__zk -force=true -c rmr "/esdc/nodes/hosts/${SYSINFO_UUID}" &> /dev/null || true
+	set +e
+	__zk -force=true -c rmr "/esdc/nodes/hosts/${SYSINFO_UUID}" &> /dev/null
+	set -e
 	_zk creater "/esdc/nodes/hosts/${SYSINFO_UUID}" "${SYSINFO_Hostname}"
 	_zk creater "/esdc/nodes/hosts/${SYSINFO_UUID}/headnode" "false"
 	_zk creater "/esdc/nodes/hosts/${SYSINFO_UUID}/hostname" "${SYSINFO_Hostname}"
