Modify installer to allow installing remote nodes (#101)
* Internal Danube Cloud services use verified SSL certificates - Closes #102 
* Added support for remote compute nodes - Closes #90

diff --git a/ansible/templates/usb/scripts/computenode.sh.j2 b/ansible/templates/usb/scripts/computenode.sh.j2
--- a/ansible/templates/usb/scripts/computenode.sh.j2
+++ b/ansible/templates/usb/scripts/computenode.sh.j2
@@ -1,7 +1,7 @@
 #!/usr/bin/bash
 
 #
-# Copyright (c) 2015-2017, Erigones, s. r. o.
+# Copyright (c) 2015-2018, Erigones, s. r. o.
 #
 
 unset LD_LIBRARY_PATH
@@ -22,6 +22,14 @@ exec 4>>/dev/console
 
 # Time to wait for each VM to setup (in seconds)
 VM_DEPLOY_TIMEOUT=600
+
+OPENSSL="/opt/local/bin/openssl"
+OPENSSL_HOME="/opt/local/etc/openssl"
+SVC_CERT_FILE_NAME="dc-erigonesd.pem"
+SVC_CERT_FILE="${OPENSSL_HOME}/${SVC_CERT_FILE_NAME}"
+QUERY_CFGDB="${ERIGONES_HOME}/bin/query_cfgdb"
+TIMEOUT="/opt/local/bin/timeout"
+
 
 # Helper functions
 function printf_log() {
@@ -80,9 +88,21 @@ if [[ -f /var/lib/setup.json ]]; then
 fi
 
 function configure_erigonesd() {
-	echo "BROKER_URL = 'amqp://{{ esdc_mgmt.rabbitmq.user }}:${RABBITMQ_PASSWORD}@${MGMT_IP}:{{ esdc_mgmt.rabbitmq.port }}/{{ esdc_mgmt.rabbitmq.vhost }}'" > /opt/erigones/core/celery/local_config.py
-	echo "CELERY_RESULT_BACKEND = 'redis://:${REDIS_PASSWORD}@${MGMT_IP}:{{ esdc_mgmt.redis.port }}/0'" >> /opt/erigones/core/celery/local_config.py
-	echo "ERIGONES_MGMT_WORKERS = ('mgmt@{{ esdc_mgmt.hostname | default('mgmt01.local') }}',)" >> /opt/erigones/core/celery/local_config.py
+	if [[ ! -f "${SVC_CERT_FILE}" ]]; then
+		fatal "SSL certificate file not present: ${SVC_CERT_FILE}"
+	fi
+
+	cat > /opt/erigones/core/celery/local_config.py << EOF
+BROKER_URL = 'amqp://{{ esdc_mgmt.rabbitmq.user }}:${RABBITMQ_PASSWORD}@${MGMT_IP}:{{ esdc_mgmt.rabbitmq.port_ssl }}/{{ esdc_mgmt.rabbitmq.vhost }}'
+CELERY_RESULT_BACKEND = 'redis://:${REDIS_PASSWORD}@${MGMT_IP}:{{ esdc_mgmt.redis.port_ssl }}/0'
+ERIGONES_MGMT_WORKERS = ('mgmt@{{ esdc_mgmt.hostname | default('mgmt01.local') }}',)
+
+import ssl
+
+BROKER_USE_SSL = { 'cert_reqs': ssl.CERT_REQUIRED, 'ca_certs': '${SVC_CERT_FILE}' }"
+REDIS_BACKEND_USE_SSL = { 'ssl_cert_reqs': ssl.CERT_REQUIRED, 'ca_certs': '${SVC_CERT_FILE}' }"
+EOF
+
 	chown root:root /opt/erigones/core/celery/local_config.py
 	chmod 0600 /opt/erigones/core/celery/local_config.py
 }
@@ -122,24 +142,64 @@ function install_archives() {
 }
 
 function __zk() {
-	zkcli="${USB_COPY}/scripts/zookeepercli"
-	args="${@}"
-
-	"${zkcli}" -servers "${CFGDB_IP}:2181" -auth_usr "esdc" -auth_pwd "${ESDC_INSTALL_PASSWORD}" ${args}
+	"${QUERY_CFGDB}" "${@}"
 }
 
 function _zk() {
-	if ! __zk -c "${@}" 2> /dev/null; then
+	if ! __zk "${@}" 2> /dev/null; then
 		fatal "Error: cfgdb command \"${@}\" failed"
 	fi
 }
 
+function _zk_noerror() {
+	# return success anyway
+	__zk "${@}" 2> /dev/null || true
+}
+
+# omit SSL certificate verification
+function _zk_noverify() {
+	_zk_noerror -k "${@}"
+}
+
+test_cfgdb_connect() {
+	if [[ -z "$(_zk_noverify get /esdc/settings)" ]]; then
+		fatal "Unable to query cfgdb"
+	fi
+}
+
+test_port_open() {
+	local host="${1}"
+	local port="${2}"
+	local waittime=5
+
+	"${TIMEOUT}" "${waittime}" nc -z "${host}" "${port}"
+}
+
+function setup_svc_ssl_cert() {
+	# download SSL cert
+	local svc_cert="$(_zk_noverify get /esdc/settings/security/services_ssl_cert)"
+
+	# the only expected case for not getting the certificate
+	# is adding v3.0.0 or later compute node to pre-v3.0.0 management
+	if [[ -z "${svc_cert}" ]]; then
+		# node must have SSL enabled...
+		# fail loudly then
+		fatal "No certificate retrieved from configuration database. Installation cannot continue."
+	fi
+
+	# save the public cert into openssl trusted certs
+	echo "${svc_cert}" > "${SVC_CERT_FILE}"
+	# rehash certificate
+	ln -s "${SVC_CERT_FILE}" "${OPENSSL_HOME}/certs/${SVC_CERT_FILE_NAME}"
+	ln -s "${SVC_CERT_FILE_NAME}" "${OPENSSL_HOME}/certs/$("${OPENSSL}" x509 -hash -noout -in "${SVC_CERT_FILE}").0"
+}
+
+# Wait for configuration database availability
 function wait_for_cfgdb() {
-	set +e
 	while true; do
 		printf_log "\r%-64s" "Waiting for cfgdb availability... "
-		if ping -n "${CFGDB_IP}" > /dev/null 2>&1; then
-			if echo "ruok" | nc -n -w 10 "${CFGDB_IP}" 2181 2> /dev/null | grep imok >/dev/null 2>&1; then
+		if ping -n "${CFGDB_IP}" 2 > /dev/null 2>&1; then
+			if test_port_open "${CFGDB_IP}" "{{ esdc_cfgdb.zookeeper.port_ssl }}"; then
 				printf_log "done\n"
 				break
 			fi
@@ -147,36 +207,61 @@ function wait_for_cfgdb() {
 		printf_log "not yet\n"
 		sleep 1
 	done
-	set -e
 }
 
-function query_cfgdb() {
-	# Wait for configuration database availability
-	wait_for_cfgdb
-
+function pull_cfgdb_data() {
 	printf_log "\r%-64s" "Retrieving Danube Cloud management configuration from cfgdb... "
 
-	_mgmt_ip=$(_zk get "/esdc/settings/rabbitmq/host")
-	_mon_ip=$(_zk get "/esdc/settings/zabbix/host")
-	_rabbitmq_password=$(_zk get "/esdc/settings/rabbitmq/password")
-	_redis_password=$(_zk get "/esdc/settings/redis/password")
+	# first search for node-specific configuration for this specific node
+	_rabbitmq_ip=$(_zk_noerror get "/esdc/settings/node/${SYSINFO_Hostname}/rabbitmq/host")
+	_redis_ip=$(_zk_noerror get "/esdc/settings/node/${SYSINFO_Hostname}/redis/host")
+	_mon_ip=$(_zk_noerror get "/esdc/settings/node/${SYSINFO_Hostname}/zabbix/host")
+	_rabbitmq_password=$(_zk_noerror get "/esdc/settings/${SYSINFO_Hostname}/rabbitmq/password")
+	_redis_password=$(_zk_noerror get "/esdc/settings/${SYSINFO_Hostname}/redis/password")
 
-	if [[ -z "${_mgmt_ip}" || -z "${_mon_ip}" || -z "${_rabbitmq_password}" || -z "${_redis_password}" ]]; then
+	if [[ "${CONFIG_remote_node}" -eq 1 ]]; then
+		# Get the remote IPs. If they do not exist, fill in cfgdb IP that was specified during install
+		# because remote cfgdb is expected to be a proxy to all services
+		# (unless explicitly specified otherwise in /esdc/settings/remote/*).
+
+		# if node-specific config is not found, search generic remote configuration
+		[[ -z "${_rabbitmq_ip}" ]] &&   _rabbitmq_ip=$(_zk_noerror get "/esdc/settings/remote/rabbitmq/host")
+		[[ -z "${_redis_ip}" ]] &&      _redis_ip=$(_zk_noerror get "/esdc/settings/remote/redis/host")
+		[[ -z "${_mon_ip}" ]] &&        _mon_ip=$(_zk_noerror get "/esdc/settings/remote/zabbix/host")
+
+		# fallback for remote node is cfgdb IP
+		[[ -z "${_rabbitmq_ip}" ]] &&   _rabbitmq_ip="${CFGDB_IP}"
+		[[ -z "${_redis_ip}" ]] &&      _redis_ip="${CFGDB_IP}"
+		[[ -z "${_mon_ip}" ]] &&       	_mon_ip="${CFGDB_IP}"
+	fi
+
+	# as a fallback, query global services settings (return error if not found)
+	[[ -z "${_rabbitmq_ip}" ]] &&           _rabbitmq_ip=$(_zk get "/esdc/settings/rabbitmq/host")
+	[[ -z "${_redis_ip}" ]] &&              _redis_ip=$(_zk get "/esdc/settings/redis/host")
+	[[ -z "${_mon_ip}" ]] &&                _mon_ip=$(_zk get "/esdc/settings/zabbix/host")
+	[[ -z "${_rabbitmq_password}" ]] &&     _rabbitmq_password=$(_zk get "/esdc/settings/rabbitmq/password")
+	[[ -z "${_redis_password}" ]] &&        _redis_password=$(_zk get "/esdc/settings/redis/password")
+
+	if [[ -z "${_rabbitmq_ip}" || -z "${_redis_ip}" || -z "${_mon_ip}" || -z "${_rabbitmq_password}" || -z "${_redis_password}" ]]; then
 		fatal "Incomplete data in configuration database, aborting setup"
 	fi
 
 	printf_log "%4s\n" "done"
 	printf_log "\r%-64s" "Registering compute node into cfgdb... "
 
-	set +e
-	__zk -force=true -c rmr "/esdc/nodes/hosts/${SYSINFO_UUID}" &> /dev/null
-	set -e
+	_zk_noerror rmr --force "/esdc/nodes/hosts/${SYSINFO_UUID}"
 	_zk creater "/esdc/nodes/hosts/${SYSINFO_UUID}" "${SYSINFO_Hostname}"
 	_zk creater "/esdc/nodes/hosts/${SYSINFO_UUID}/headnode" "false"
 	_zk creater "/esdc/nodes/hosts/${SYSINFO_UUID}/hostname" "${SYSINFO_Hostname}"
+	if [[ -n "${CONFIG_remote_node}" ]]; then
+		_zk creater "/esdc/nodes/hosts/${SYSINFO_UUID}/is_remote" "${CONFIG_remote_node}"
+	else
+		_zk creater "/esdc/nodes/hosts/${SYSINFO_UUID}/is_remote" "0"
+	fi
 
-	MGMT_IP=${_mgmt_ip}
 	MON_IP=${_mon_ip}
+	RABBITMQ_IP=${_rabbitmq_ip}
+	REDIS_IP=${_redis_ip}
 	RABBITMQ_PASSWORD=${_rabbitmq_password}
 	REDIS_PASSWORD=${_redis_password}
 
@@ -250,9 +335,11 @@ generate_ssh_keys
 
 # Metatada for installation
 CFGDB_IP="${CONFIG_cfgdb_admin_ip}"
-ESDC_INSTALL_PASSWORD="${CONFIG_esdc_install_password}"
 
-query_cfgdb
+wait_for_cfgdb
+test_cfgdb_connect
+setup_svc_ssl_cert
+pull_cfgdb_data
 configure_erigonesd
 configure_zabbix
 
diff --git a/ansible/templates/usb/scripts/headnode.sh.j2 b/ansible/templates/usb/scripts/headnode.sh.j2
--- a/ansible/templates/usb/scripts/headnode.sh.j2
+++ b/ansible/templates/usb/scripts/headnode.sh.j2
@@ -1,7 +1,7 @@
 #!/usr/bin/bash
 
 #
-# Copyright (c) 2015-2017, Erigones, s. r. o.
+# Copyright (c) 2015-2018, Erigones, s. r. o.
 #
 
 unset LD_LIBRARY_PATH
@@ -22,6 +22,20 @@ exec 4>>/dev/console
 
 # Time to wait for each VM to setup (in seconds)
 VM_DEPLOY_TIMEOUT=600
+
+# global vars
+ERIGONES_HOME="/opt/erigones"
+OPENSSL="/opt/local/bin/openssl"
+OPENSSL_HOME="/opt/local/etc/openssl"
+SVC_CERT_FILE_NAME="dc-erigonesd.pem"
+SVC_CERT_FILE="${OPENSSL_HOME}/${SVC_CERT_FILE_NAME}"
+QUERY_CFGDB="${ERIGONES_HOME}/bin/query_cfgdb"
+TIMEOUT="/opt/local/bin/timeout"
+
+# certificate for DC internal services 
+SVC_CERT=
+SVC_KEY=
+
 
 # Helper functions
 function printf_log() {
@@ -95,10 +109,63 @@ function configure_imgadm() {
 	fi
 }
 
+# change all newlines to '\n'
+function escape_cert_data() {
+	local certfile="$1"
+
+	if [[ -f "${certfile}" ]]; then
+		sed -re 's/$/\\n/g' "${certfile}" | tr -d '\n'
+	fi
+}
+
+function generate_svc_ssl_cert() {
+	local svc_cert_tmpfile="/tmp/svc_$$_cert.pem"
+	local svc_key_tmpfile="/tmp/svc_$$_key.pem"
+
+	# update openssl conf to allow alternate names
+	cat << EOF >> /opt/local/etc/openssl/openssl.cnf
+
+[SAN]
+subjectAltName = {{ esdc_mgmt.erigonesd.subjectAltName }}
+EOF
+
+	UMASK_OLD="$(umask)"
+	umask 0077
+	"${OPENSSL}" req -x509 -sha256 -nodes -days 10000 -subj '/CN=esdc.local/O=Danube Cloud/' -reqexts SAN -extensions SAN -newkey rsa:8192 -keyout "${svc_key_tmpfile}" -out "${svc_cert_tmpfile}"
+	umask "${UMASK_OLD}"
+
+	if [[ ! -s "${svc_cert_tmpfile}" ]] || [[ ! -s "${svc_key_tmpfile}" ]]; then
+		fatal "Services SSL cert was not generated properly"
+	fi
+
+	SVC_CERT="$(escape_cert_data "${svc_cert_tmpfile}")"
+	SVC_KEY="$(escape_cert_data "${svc_key_tmpfile}")"
+
+	# save the public cert into openssl trusted certs
+	cp "${svc_cert_tmpfile}" "${SVC_CERT_FILE}"
+	# rehash certificate
+	ln -s "${SVC_CERT_FILE}" "${OPENSSL_HOME}/certs/${SVC_CERT_FILE_NAME}"
+	ln -s "${SVC_CERT_FILE_NAME}" "${OPENSSL_HOME}/certs/$("${OPENSSL}" x509 -hash -noout -in "${SVC_CERT_FILE}").0"
+
+	rm -f "${svc_key_tmpfile}" "${svc_cert_tmpfile}"
+}
+
 function configure_erigonesd() {
-	echo "BROKER_URL = 'amqp://{{ esdc_mgmt.rabbitmq.user }}:${RABBITMQ_PASSWORD}@${MGMT_IP}:{{ esdc_mgmt.rabbitmq.port }}/{{ esdc_mgmt.rabbitmq.vhost }}'" > /opt/erigones/core/celery/local_config.py
-	echo "CELERY_RESULT_BACKEND = 'redis://:${REDIS_PASSWORD}@${MGMT_IP}:{{ esdc_mgmt.redis.port }}/0'" >> /opt/erigones/core/celery/local_config.py
-	echo "ERIGONES_MGMT_WORKERS = ('mgmt@{{ esdc_mgmt.hostname | default('mgmt01.local') }}',)" >> /opt/erigones/core/celery/local_config.py
+	if [[ ! -f "${SVC_CERT_FILE}" ]]; then
+		fatal "SSL certificate file not present: ${SVC_CERT_FILE}"
+	fi
+
+	cat > /opt/erigones/core/celery/local_config.py << EOF
+BROKER_URL = 'amqp://{{ esdc_mgmt.rabbitmq.user }}:${RABBITMQ_PASSWORD}@${MGMT_IP}:{{ esdc_mgmt.rabbitmq.port_ssl }}/{{ esdc_mgmt.rabbitmq.vhost }}'
+CELERY_RESULT_BACKEND = 'redis://:${REDIS_PASSWORD}@${MGMT_IP}:{{ esdc_mgmt.redis.port_ssl }}/0'
+ERIGONES_MGMT_WORKERS = ('mgmt@{{ esdc_mgmt.hostname | default('mgmt01.local') }}',)
+
+import ssl
+
+BROKER_USE_SSL = { 'cert_reqs': ssl.CERT_REQUIRED, 'ca_certs': '${SVC_CERT_FILE}' }"
+REDIS_BACKEND_USE_SSL = { 'ssl_cert_reqs': ssl.CERT_REQUIRED, 'ca_certs': '${SVC_CERT_FILE}' }"
+EOF
+
 	chown root:root /opt/erigones/core/celery/local_config.py
 	chmod 0600 /opt/erigones/core/celery/local_config.py
 }
@@ -179,6 +246,8 @@ function _build_vmmanifest() {
 				-e "s|@MON_IP@|${MON_IP}|" \
 				-e "s|@ROOT_AUTHORIZED_KEYS@|${ROOT_AUTHORIZED_KEYS}|" \
 				-e "s|@ESDC_INSTALL_PASSWORD@|${ESDC_INSTALL_PASSWORD}|" \
+				-e "s|@ERIGONESD_SSL_CERT@|${SVC_CERT}|" \
+				-e "s|@ERIGONESD_SSL_KEY@|${SVC_KEY}|" \
 				"${template}" > "${manifest}"
 		;;
 
@@ -228,6 +297,9 @@ function _build_vmmanifest() {
 				-e "s|@PGSQL_PDNS_PASSWORD@|${PGSQL_PDNS_PASSWORD}|" \
 				-e "s|@PGSQL_MGMT_MON_PASSWORD@|${PGSQL_MGMT_MON_PASSWORD}|" \
 				-e "s|@ESDC_ADMIN_EMAIL@|${ZABBIX_ADMIN_EMAIL}|" \
+				-e "s|@ERIGONESD_SSL_CERT@|${SVC_CERT}|" \
+				-e "s|@ERIGONESD_SSL_KEY@|${SVC_KEY}|" \
+				-e "s|@CFGDB_IP@|${CFGDB_IP}|" \
 				"${template}" > "${manifest}"
 		;;
 
@@ -395,12 +467,38 @@ function install_archives() {
 	fi
 }
 
-function _zk() {
-	zkcli="${USB_COPY}/scripts/zookeepercli"
-	cmd="${@}"
+test_port_open() {
+	local host="${1}"
+	local port="${2}"
+	local waittime=5
 
-	if ! "${zkcli}" -servers "${CFGDB_IP}:2181" -auth_usr "esdc" -auth_pwd "${ESDC_INSTALL_PASSWORD}" -c ${cmd} &> /dev/null; then
-		fatal "Error: cfgdb command \"${cmd}\" failed"
+	"${TIMEOUT}" "${waittime}" nc -z "${host}" "${port}"
+}
+
+# Wait for configuration database availability
+function wait_for_cfgdb() {
+	while true; do
+		printf_log "\r%-64s" "Waiting for cfgdb availability... "
+		if ping -n "${CFGDB_IP}" 1 > /dev/null 2>&1; then
+			if test_port_open "${CFGDB_IP}" "{{ esdc_cfgdb.zookeeper.port_ssl }}"; then
+				printf_log "done\n"
+				break
+			fi
+		fi
+		printf_log "not yet\n"
+		sleep 1
+	done
+}
+
+function _zk() {
+	if ! "${QUERY_CFGDB}" "${@}" 2> /dev/null; then
+		fatal "Error: cfgdb command \"${@}\" failed"
+	fi
+}
+
+test_cfgdb_connect() {
+	if [[ -z "$("${QUERY_CFGDB}" get /esdc/settings 2> /dev/null)" ]]; then
+		fatal "Unable to query cfgdb"
 	fi
 }
 
@@ -415,10 +513,12 @@ function configure_cfgdb() {
 	_zk creater /esdc/settings/rabbitmq/password "${RABBITMQ_PASSWORD}"
 	_zk creater /esdc/settings/rabbitmq/host "${MGMT_IP}"
 	_zk creater /esdc/settings/rabbitmq/port "{{ esdc_mgmt.rabbitmq.port }}"
+	_zk creater /esdc/settings/rabbitmq/port_ssl "{{ esdc_mgmt.rabbitmq.port_ssl }}"
 	_zk creater /esdc/settings/rabbitmq/vhost "{{ esdc_mgmt.rabbitmq.vhost }}"
 
 	_zk creater /esdc/settings/redis/host "${MGMT_IP}"
 	_zk creater /esdc/settings/redis/port "{{ esdc_mgmt.redis.port }}"
+	_zk creater /esdc/settings/redis/port_ssl "{{ esdc_mgmt.redis.port_ssl }}"
 	_zk creater /esdc/settings/redis/password "${REDIS_PASSWORD}"
 
 	_zk creater /esdc/settings/pgsql_esdc/host "${MGMT_IP}"
@@ -438,6 +538,8 @@ function configure_cfgdb() {
 	_zk creater /esdc/settings/zabbix/smtp_email "${ZABBIX_SMTP_EMAIL}"
 	_zk creater /esdc/settings/zabbix/esdc_username "${ZABBIX_ESDC_USERNAME}"
 	_zk creater /esdc/settings/zabbix/esdc_password "${ZABBIX_ESDC_PASSWORD}"
+
+	_zk creater /esdc/settings/security/services_ssl_cert "$(cat ${SVC_CERT_FILE})"
 
 	_zk creater "/esdc/nodes/hosts/${SYSINFO_UUID}" "${SYSINFO_Hostname}"
 	_zk creater "/esdc/nodes/hosts/${SYSINFO_UUID}/headnode" "true"
@@ -566,6 +668,7 @@ domainname="${CONFIG_domainname:-"${CONFIG_dns_domain}"}"
 [[ -z "${domainname}" ]] && domainname="example.com"
 ZABBIX_SMTP_EMAIL="${CONFIG_sender_email:-"monitoring@${domainname}"}"
 
+generate_svc_ssl_cert
 configure_erigonesd
 configure_zabbix
 
@@ -577,6 +680,8 @@ MGMT_SSH_KEY="$(get_mgmt_ssh_key)"
 
 install_isos
 configure_imgadm
+wait_for_cfgdb
+test_cfgdb_connect
 configure_cfgdb
 install_images
 import_smf_manifests
diff --git a/ansible/templates/usb/scripts/prompt-config.sh.j2 b/ansible/templates/usb/scripts/prompt-config.sh.j2
--- a/ansible/templates/usb/scripts/prompt-config.sh.j2
+++ b/ansible/templates/usb/scripts/prompt-config.sh.j2
@@ -7,7 +7,7 @@
 
 #
 # Copyright (c) 2017, Joyent, Inc.
-# Copyright (c) 2017, Erigones, s. r. o.
+# Copyright (c) 2018, Erigones, s. r. o.
 #
 
 # XXX - TODO
@@ -1508,6 +1508,7 @@ create_zpools()
 {% if usb_type != "hn" %}
 check_cfgdb()
 {
+	local ec
 	trap "" SIGINT
 	printf "Checking cfgdb availability..."
 	echo "ruok" | nc -n -w 10 "${cfgdb_admin_ip}" 2181 2> /dev/null | grep imok >/dev/null 2>&1
@@ -1525,18 +1526,23 @@ check_cfgdb()
 
 query_cfgdb()
 {
-	local zkcli="${USBMNT}/scripts/zookeepercli"
-
+	local curl_ec
+	local curl_out
+	local json_ec
+	local zk_ec
 	trap "" SIGINT
 	printf "Accessing cfgdb..."
-	datacenter_name=$("${zkcli}" -servers "${cfgdb_admin_ip}:2181" -auth_usr "esdc" \
-		-auth_pwd "${esdc_install_password}" -c get /esdc/settings/dc/datacenter_name 2>/var/tmp/zk-error)
-	ec=$?
 
-	if [[ "${ec}" -eq 0 ]]; then
+	curl_out=$(curl -m 15 -k -s -S -H "zk-username:esdc" -H "zk-password:${esdc_install_password}" "https://${cfgdb_admin_ip}:12181/esdc/settings/dc/datacenter_name" 2>&1)
+	curl_ec=$?
+	zk_ec="$(echo "${curl_out}" | json "returncode" 2> /dev/null)"
+	json_ec=$?
+
+	if [[ "${curl_ec}" -eq 0 ]] && [[ "${json_ec}" -eq 0 ]] && [[ "${zk_ec}" == "0" ]]; then
+		datacenter_name="$(echo "${curl_out}" | json "stdout")"
 		printf "OK\n"
 	else
-		printf "ERROR ($(nawk -F 'zk: ' '{ print $2 }' /var/tmp/zk-error))\n"
+		printf "ERROR (${curl_out})\n"
 	fi
 
 	trap sig_doshell SIGINT
@@ -1849,9 +1855,9 @@ The tags can be added or modified also later by the nictagadm command.\n\n"
 	printheader "Networking - default gateway"
 	message="
 The default gateway will determine which router will be used to connect
-this compute node to other networks. This will almost certainly be the router
-connected to your 'admin' network. Use 'none' if you have no gateway
-or you rely only on the dhcp.\n\n"
+this compute node to other networks. This is probably the router
+connected to your 'admin' or 'external' network.
+Use 'none' if you have no gateway or you rely only on the dhcp.\n\n"
 
 	if [[ $(getanswer "skip_instructions") != "true" ]]; then
 		printf "$message"
@@ -2045,6 +2051,21 @@ web management.\n\n"
 	[[ -z "${cfgdb_admin_ip}" ]] && cfgdb_admin_ip="$(discover_cfgdb)"
 	prompt_host_ok_val "Configuration database IP address" "${cfgdb_admin_ip}" "cfgdb_admin_ip"
 	cfgdb_admin_ip="${val}"
+	if [[ ${advanced_install} -eq 1 ]] && ! ip_from_subnet "${cfgdb_admin_ip}" "${admin_ip}" "${admin_netmask}" ; then
+		# the CFGDB IP is outside the subnet
+		message="
+You have entered an IP address outside the admin subnet.
+That suggests this is a remote compute node.
+A remote compute node connects to the management VMs via the internet
+(external network) instead of connecting directly using the admin network.\n"
+		if [[ $(getanswer "skip_instructions") != "true" ]]; then
+			printf "$message"
+		fi
+		promptbool "Is this a remote compute node? (y/n)" "y" "remote_node"
+		remote_node=${val}
+	else
+		remote_node=0
+	fi
 	skip_cfgdb_check=$(getanswer "skip_cfgdb_check")
 	[[ -z ${skip_cfgdb_check} || ${skip_cfgdb_check} != "true" ]] && check_cfgdb
 {% endif %}
@@ -2075,6 +2096,12 @@ the first compute node installation.\n\n"
 	if [[ -z ${skip_cfgdb_check} || ${skip_cfgdb_check} != "true" ]]; then
 		if ! query_cfgdb; then  # This will set the datacenter_name
 			print_warning "Failed to read data from the configuration database"
+		fi
+		if [[ "${remote_node}" -eq 1 ]]; then
+			datacenter_name="${datacenter_name} remote"
+			echo
+			promptval "Enter remote DC name" "${datacenter_name}" "datacenter_name"
+			datacenter_name="$val"
 		fi
 	fi
 {% endif %}
@@ -2290,6 +2317,9 @@ echo "img_admin_ip=${img_admin_ip}" >>$tmp_config
 echo "cfgdb_admin_ip=${cfgdb_admin_ip}" >>$tmp_config
 echo "esdc_install_password='${esdc_install_password}'" >>$tmp_config
 echo "install_to_hdd=${install_to_hdd}" >>$tmp_config
+if [[ -n "${remote_node}" ]]; then
+	echo "remote_node=${remote_node}" >>$tmp_config
+fi
 echo  >>$tmp_config
 # END: Danube Cloud settings
 printf "%4s\n" "done"
