Update query_cfgdb

diff --git a/ansible/templates/usb/scripts/prompt-config.sh.j2 b/ansible/templates/usb/scripts/prompt-config.sh.j2
--- a/ansible/templates/usb/scripts/prompt-config.sh.j2
+++ b/ansible/templates/usb/scripts/prompt-config.sh.j2
@@ -1508,6 +1508,7 @@ create_zpools()
 {% if usb_type != "hn" %}
 check_cfgdb()
 {
+	local ec
 	trap "" SIGINT
 	printf "Checking cfgdb availability..."
 	echo "ruok" | nc -n -w 10 "${cfgdb_admin_ip}" 2181 2> /dev/null | grep imok >/dev/null 2>&1
@@ -1525,18 +1526,23 @@ check_cfgdb()
 
 query_cfgdb()
 {
-	local zkcli="${USBMNT}/scripts/zookeepercli"
-
+	local curl_ec
+	local curl_out
+	local json_ec
+	local zk_ec
 	trap "" SIGINT
 	printf "Accessing cfgdb..."
-	datacenter_name=$("${zkcli}" -servers "${cfgdb_admin_ip}:2181" -auth_usr "esdc" \
-		-auth_pwd "${esdc_install_password}" -c get /esdc/settings/dc/datacenter_name 2>/var/tmp/zk-error)
-	ec=$?
 
-	if [[ "${ec}" -eq 0 ]]; then
+	curl_out=$(curl -m 15 -k -s -S -H "zk-username:esdc" -H "zk-password:${esdc_install_password}" "https://${cfgdb_admin_ip}:12181/esdc/settings/dc/datacenter_name" 2>&1)
+	curl_ec=$?
+	zk_ec="$(echo "${curl_out}" | json "returncode" 2> /dev/null)"
+	json_ec=$?
+
+	if [[ "${curl_ec}" -eq 0 ]] && [[ "${json_ec}" -eq 0 ]] && [[ "${zk_ec}" == "0" ]]; then
+		datacenter_name="$(echo "${curl_out}" | json "stdout")"
 		printf "OK\n"
 	else
-		printf "ERROR ($(nawk -F 'zk: ' '{ print $2 }' /var/tmp/zk-error))\n"
+		printf "ERROR (${curl_out})\n"
 	fi
 
 	trap sig_doshell SIGINT
